INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE) VALUES (10001, 'Robert', current_date());
INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE) VALUES (10002, 'Charlie', current_date());
INSERT INTO USER_DETAILS(ID, NAME, BIRTH_DATE) VALUES (10003, 'Harry', current_date());
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20001, 'I want to learn AWS', 10001);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20003, 'I want to learn Devops', 10001);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20004, 'I want to get certified in Java', 10002);
INSERT INTO POST(ID, DESCRIPTION, USER_ID) VALUES (20005, 'I want to learn Multi Cloud', 10002);